Add keycloak SAML auth automation for AMG
aws-samples/one-observability-demo pull request #243
Opened 2023-09-04 22:51 UTC by iamsouravin

*Issue #, if available:* Fixes #242

*Description of changes:*
1. Add missing `AddTags` permission to AWS Load Balancer controller IRSA policy.
2. Update keycloak service annotations to create `internet-facing` NLB.
3. Upgrade keycloak version and add automation scripts for setup and cleanup.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-09-05 18:35 UTC, bonclay7 commented on PetAdoptions/keycloak-setup.sh
> +export KEYCLOAK_REALM_AMG=amg
We probably need to take these as inputs and fail the script if they are not provided. People can decide to name their MG workspace differently for example.

2023-09-05 18:46 UTC, bonclay7 requested changes
This is AMAZING! It just works with one command, thanks for doing this. I just have credentials to use and log in, perfect ❤️

We should sanitize the inputs to make it flexible and fail (or use defaults) if nothing is provided

2023-09-05 18:46 UTC, bonclay7 commented on PetAdoptions/keycloak-cleanup.sh
> +export KEYCLOAK_NAMESPACE=keycloak
Same thing here, we need to take inputs an verify them

2023-09-05 18:46 UTC, bonclay7 commented on PetAdoptions/keycloak-setup.sh
> +export KEYCLOAK_REALM_AMG=amg
We probably need to take these as inputs and fail the script if they are not provided or use overridable default values. People can decide to name their MG workspace differently for example.

2023-09-07 06:00 UTC, iamsouravin commented
The scripts have been parameterized to accept the configurable fields like cluster name, workspace name, keycloak namespace, keycloak realm, etc.

2023-09-07 13:46 UTC, bonclay7 approved these changes
Awesome, LGTM

2023-09-07 16:20 UTC, bonclay7 commented
Closing this for duplicate

2023-09-07 16:20 UTC, closed without merging